# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-30 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('telephone', models.BigIntegerField()),
                ('heure_ouverture', models.TimeField(verbose_name="Heure d'ouverture ")),
                ('heure_fermeture', models.TimeField(verbose_name='Heure de fermeture')),
                ('email', models.EmailField(max_length=254)),
                ('info_supp', models.TextField(verbose_name='Information supplementaire')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('telephone', models.BigIntegerField()),
                ('info_supp', models.TextField(null=True, verbose_name='Information supplementaire')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='pharmacien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pharmacien'),
        ),
    ]
