# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-30 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='valide',
            field=models.BooleanField(default=False, verbose_name='Activer'),
        ),
    ]
