# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-30 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pharmacie_valide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacien',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacien',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
