# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-31 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pharmacie_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
