# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-03 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170831_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacien',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pharmacien',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='pharmacien',
            name='prenom',
        ),
    ]
